### ISSUE TITLE
Investigate NER and CRF

### ISSUE THREAD

**Issue by kbrose** [chicago-justice-project/article-tagging#27]
Investigate Named Entity Recognition and the related field of Conditional Random Fields for the purpose of location extraction from articles.

**Comment by pandey** [comment]
After our discussion at ChiHackNight on August 29, I developed a function to extract locations from articles using the NLTK chunk parser. It parses POS tags using regex to identify locations such as "2000 block of South Halsted Street" and "2000 South Halsted Street". I'm not sure which methods you've tested so far for location extraction, but if my function sounds useful, I can contribute the code to the project.

I wrote two other functions that use the data generated by the above method. The first validates bare addresses, such as "South Halsted Street", against the City of Chicago's 'Street Names' database. The second uses the Google Map Geocoding API to retrieve geographical coordinates for a valid address.

In the next couple of days I'll look over the existing code in the project to evaluate your current extraction methods.

**Comment by kbrose** [comment]
We looked at a regex based approach. I'm not convinced that a regex solution would end up with better FPR/TPR than a probabilistic approach, but the only way to be sure of that is to check it against ground truth data. We just updated the data dump script last night so hopefully next week I'll have some of that ground truth location extraction data.

If you want to see how others have tried to use regex's for this problem, check out everyblock. I forked their code here: https://github.com/kbrose/everyblock

Specifically, you may want to look at the files in https://github.com/kbrose/everyblock/tree/master/ebdata/ebdata/nlp

**Comment by pandey** [comment]
Thank you for that feedback. I just glanced at the everyblock code. The NLTK chunker is a bit different. Instead of pure regex, the chunker operates on POS-tags. For instance, the phrase `"2700 block of South Halsted Street"` is tagged as:

```
[('7200', 'CD'), ('block', 'NN'), ('of', 'IN'), ('South', 'NNP'), ('Halstead', 'NNP'), ('Street', 'NNP')]

```
A chunking grammar, such as `<CD><NN><IN><NNP>*`, will extract sequences that match the pattern. It's a bit less ruled-based than pure regex parsing, as is done by everyblock, but it is indeed conceptually similar.

I'll add the Jupyter notebook to my git after I've done more testing, so you can test for yourself. I agree, a probabilistic approach would be best. I'll try to develop a classification chunker and see how that works out. It will be very useful to test with the forthcoming ground truth data.

**Comment by pandey** [comment]
Update: decided to test a CRF approach today using CRFsuite. Preliminary results look promising. It's a bit time consuming as I have to build a custom corpus to use for training, which involves adding IOB annotations to tokens that are to be classified as a sequence. The data from the corpus consists of random paragraphs that have been extracted from the 2gb newsarticles_article.csv file.

Speaking of that monster file: please excuse my ignorance: is there a particular reason that all the articles are aggregated into a single file? Did you guys consider storing each article as a separate file?, ie. as done for the Groningen Meaning Bank: http://gmb.let.rug.nl/data.php. Individual files for articles would be very handy for visual inspection, corpus generation, EDA, and other training purposes, rather than having to process a huge file.

In any case, I'm really enjoying working on this issue. Just sorry that I can't allocate more time than I already am.

**Comment by kbrose** [comment]
Good to hear, I just updated the loading functions to handle the new data format which will have some of the human coded locations. If you find yourself spending a lot of time manually tagging articles it would probably be good to have you do that through the actual CJP interface so that we can collect that data and have everyone benefit from it.

No one else is working on the approaches described above as far as I know so no worries about duplicating effort.

Re: 2 GB file -- that was what was easiest for people working on scrapers/volunteer web UI and no one's asked for anything else. As long as you have the memory to pull it all in once it should be pretty straightforward to process/save it in the way you described. If you do end up writing that please submit that piece of code in a PR because others may find it useful.

If you're using [pandas to load the CSV](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html) you could also look at the `nrows` and `skiprows` parameters. They will probably provide everything you need if you do not have enough memory.

**Comment by kbrose** [comment]
Closing in favor of #62.
